import { z } from "zod";

export const EnvSchema = z.object({});

export const QueryParamsSchema = z.object({
  sortBy: z.string().nullable().optional(),
  sortOrder: z.enum(["asc", "desc"]).nullable().optional(),
  limit: z.string().nullable().optional(),
  page: z.string().nullable().optional(),
  search: z.string().nullable().optional(),
  filters: z.record(z.string(), z.string()).nullable().optional(),
});

export const UserDataSchema = z.object({
  userId: z.number().int(),
  firstName: z.string().min(3, "First name is required"),
  lastName: z.string().min(3, "Last name is required"),
  email: z.string().email("Invalid email"),
  roleId: z.number().int(),
  roleName: z.string(),
});

export const AuthUserSchema = UserDataSchema.extend({
  superAdmin: z.boolean(),
});

export const JwtPayloadSchema = UserDataSchema.extend({
  iat: z.number(),
  exp: z.number(),
});

// Reklamacije Schemas

export const ReklamacijaSchema = z.object({
  idReklamacije: z.number().int().nullable().optional(), // autogenerated
  brojReklamacije: z.string().min(3, "Broj reklamacije is required"),
  zemljaReklamacije: z.enum(["SRBIJA", "CRNA_GORA"], "Zemlja reklamacije is required"),
  datumPrijema: z.coerce.date().nullable().optional(),
  odgovornaOsoba: z.string().nullable().optional(),
  imePrezime: z.string().min(3, "Ime i prezime is required"),
  adresa: z.string().nullable().optional(),
  telefon: z
    .string()
    .min(6, "Telefon is required and must have at least 6 characters")
    .max(20, "Telefon must have at most 20 characters")
    .regex(/^[\d+\s\-()/]+$/, "Telefon contains invalid characters"),
  email: z.string().email("invalid email").nullable().optional(),
  datumKupovine: z.coerce.date().nullable().optional(),
  brojRacuna: z.string().min(3, "Broj racuna is required").nullable().optional(),
  nazivProizvoda: z.string().nullable().optional(),
  opisReklamacije: z.string().min(10, "Opis reklamacije is too short").nullable().optional(),
  datumOdgovora: z.coerce.date().nullable().optional(),
  opisOdluke: z.string().min(10, "Opis odluke is too short").nullable().optional(),
  komentar: z.string().nullable().optional(),
  smsSent: z.boolean().default(false),
  statusReklamacije: z.enum(["PRIJEM", "OBRADA", "OPRAVDANA", "NEOPRAVDANA", "DODATNI_ROK"], "Status reklamacije is required"),
  files: z.array(z.string().min(5, "File name is required")).nullable().optional(),
});

// Otpad Schemas

export const VrstaOtpadaSchema = z.object({
  id: z.number().int(),
  vrstaOtpada: z.string().min(3, "Vrsta otpada is required"),
});

export const OtpadProizvodSchema = z.object({
  id: z.number().int(),
  proizvod: z.string().min(3, "Proizvod is required"),
});

export const JciProizvodiSchema = z.object({
  id: z.number().int(),
  proizvod: z.string().min(3, "Proizvod is required"),
  ProizvodMasaOtpada: z.array(
    z.object({
      masa: z.number("Masa is required"),
      VrstaOtpada: VrstaOtpadaSchema,
    })
  ),
});

export const JciPodaciSchema = z.object({
  id: z.number().int(),
  zemlja: z.enum(["SRBIJA", "CRNA_GORA"], "Zemlja is required"),
  datum: z.coerce.date("Datum is required"),
  operacija: z.enum(["UVOZ", "IZVOZ"], "Operacija is required"),
  brojJci: z.string("Broj JCI is required"),
  files: z.array(z.string().min(1, "File name is required")).nullable().optional(),
  jciProizvodi: z.array(
    z.object({
      kolicina: z.number("Kolicina is required"),
      proizvod: JciProizvodiSchema,
    })
  ),
});

// Nabavke Schemas

export const NabavkeProizvodSchema = z.object({
  id: z.number().int(),
  naziv: z.string().min(5, "Naziv proizvoda is required"),
  SKU: z.string().min(5, "SKU proizvoda is required"),
});

export const NabavkeSadrzajSchema = z.object({
  id: z.number().int(),
  kolicina: z.number("Kolicina is required"),
  proizvod: NabavkeProizvodSchema,
  cena: z.number("Cena is required"),
});

export const PorudzbinaSchema = z.object({
  id: z.number().int(),
  proFaktura: z.string().min(3, "Broj pro-fakture is required"),
  dobavljac: z.string().min(5, "Dobavljač is required"),
  spediter: z.string().min(5, "Spediter is required").nullable().optional(),
  datumPorudzbine: z.coerce.date("Datum porudžbine is required"),
  datumPolaska: z.coerce.date().nullable().optional(),
  datumPrijema: z.coerce.date().nullable().optional(),
  brojKontejnera: z.string().min(3).nullable().optional(),
  komentar: z.string().nullable().optional(),
  status: z.enum(["NACRT", "PROIZVODNJA", "TRANZIT", "PRIMLJENA"]),
  zemlja: z.enum(["SRBIJA", "CRNA_GORA"]),
  sadrzaj: z.array(NabavkeSadrzajSchema),
  files: z.array(z.string().min(5, "File name is required")).nullable().optional(),
});
